Repository flyingcircusio/fc-nixos, pull requests merged in 2025-05, with the labels that each got.

#1453 fc-luks: fix external header backup
  pkgs/fc/ceph/src/fc/ceph/backup.py
  pkgs/fc/ceph/src/fc/ceph/luks/checks.py
  pkgs/fc/ceph/src/fc/ceph/luks/manage.py
  pkgs/fc/ceph/src/fc/ceph/tests/test_luks_dump.py
Labels: risk: 2, urgency: 1

#1448 s3users: error when unknown error occurs
  changelog.d/20250430_103535_PL-133656-s3users-exit-when-unknown-error-occurs_scriv.md
  pkgs/fc/agent/fc/manage/s3users.py
  pkgs/fc/agent/fc/manage/tests/test_s3users.py
Labels: risk: 3, urgency: 5

#1445 Update FRR and add extra patch for netlink batch message handling
  pkgs/frr/0001-Don-t-throw-error-when-log-directory-already-exists.patch
  pkgs/frr/0002-zebra-dplane-sleep-after-writing-batches-to-netlink.patch
  pkgs/overlay.nix
Labels: risk: 3, urgency: 2

#1442 nixos/default-packages: remove atop
  changelog.d/20250429_131920_fc-24.11-dev_scriv.md
  doc/src/base.md
  nixos/platform/packages.nix
Labels: risk: 1, urgency: 4

#1438 antivirus: fix listen config on devhosts
  changelog.d/20250428_161054_PL-133648-fix-clamav-on-devhost_scriv.md
  nixos/infrastructure/dev-vm.nix
Labels: risk: 2, urgency: 1

#1440 [PL-133484] nixos/nix-version: upgrade to 2.25
  changelog.d/20250429_115138_PL-133484-nix-2.25_scriv.md
  nixos/platform/nix.nix
  tests/nix-version.nix
Labels: risk: 3, urgency: 1

#1468 [PL-133637] nixos/slurm: return nodes to service after unexpected reboot
  changelog.d/20250508_154517_PL-133637-slurm-returntoservice_scriv.md
  nixos/roles/slurm/default.nix
Labels: risk: 2, urgency: 2

#1475 Pl 133666 haproxy cfg vs conf
  changelog.d/20250513_093854_PL-133666-haproxy-cfg-vs-conf_scriv.md
  nixos/services/haproxy/README.md
  nixos/services/haproxy/default.nix
Labels: risk: 2

#1477 [PL-133352] remove old pcre test
  changelog.d/20250513_160147_PL-133352-remove-old-pcre-test_scriv.md
  tests/default.nix
  tests/lamp/package-test.nix
Labels: risk: 1, urgency: 1

#1481 gitlab: generate ActiveRecord encryption secrets
  changelog.d/20250515_124630_gitlab-activerecord-secrets-24.11_scriv.md
  nixos/roles/gitlab.nix
Labels: risk: 1, urgency: 4

#1491 [24.11] network: move network-setup resstart to nixpkgs
  flake.lock
  nixos/platform/network.nix
  release/versions.json
Labels: risk: 1, urgency: 4, auto-merge scheduled

#1490 [25.05] network: move network-setup resstart to nixpkgs
  flake.lock
  nixos/platform/network.nix
  release/versions.json
Labels: risk: 1, urgency: 4

#1493 services/mail: do not hardcode postsrsd socket
  nixos/services/mail/default.nix
Labels: risk: 2, urgency: 2

#1499 [PL-133581] fix roles.loki options and configuration templating
  changelog.d/20250522_111955_HEAD_scriv.md
  nixos/roles/loki.nix
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1507 [25.05] merge in fc-24.11-dev (2025-05-26)
  changelog.d/20250509_135702_PL-133685-fix-reboot-schedule-on-specialisation_scriv.md
  changelog.d/20250520_165012_PL-133563-PL-133583-redis-role-rework_scriv.md
  changelog.d/20250520_165054_PL-133563-PL-133583-redis-role-rework_scriv.md
  changelog.d/20250522_111955_HEAD_scriv.md
  changelog.d/CHANGELOG.md
  doc/src/redis.md
  nixos/roles/gitlab.nix
  nixos/roles/loki.nix
  nixos/services/redis.nix
  nixos/services/telegraf/default.nix
  pkgs/fc/agent/src/fc/util/nixos.py
  release/package-versions.json
  tests/redis.nix
Labels: risk: 2, urgency: 4, auto-merge scheduled

#1515 [PL-133563] services/redis: fix case with no password and Unix socket
  nixos/services/redis.nix
  tests/redis.nix
Labels: risk: 1, urgency: 4, auto-merge scheduled

#1514 [24.11] Remove timer indirection for keepalived service
  nixos/roles/router/default.nix
Labels: risk: 2, urgency: 1, auto-merge scheduled

#1510 [PL-133702] nginx json log format
  changelog.d/20250522_102612_HEAD_scriv.md
  nixos/services/nginx/default.nix
Labels: enhancement, risk: 1, urgency: 2, auto-merge scheduled

#1498 [24.11] nginx json log format
  changelog.d/20250522_102612_HEAD_scriv.md
  nixos/services/nginx/default.nix
Labels: enhancement, risk: 1, urgency: 2, auto-merge scheduled
