Repository flyingcircusio/fc-nixos, pull requests merged in 2025-09, with the labels that each got.

#1759 Router: add options for configuration of the query source addresses used by Bind
  nixos/roles/router/bind/default.nix
  nixos/roles/router/bind/named.conf
  nixos/roles/router/default.nix
Labels: risk: 2, urgency: 3, auto-merge scheduled, backport fc-25.11-dev

#1757 roles.jitsi: Fix prosodyctl failures by conditionally loading TURN credentials
  changelog.d/20250901_180411_PL-133672-prosodyctl-secrets_scriv.md
  nixos/roles/jitsi/default.nix
Labels: risk: 2, urgency: 3, auto-merge scheduled, backport fc-25.11-dev

#1767 Remove deprecated gateway addresses from WHQ keepalived config
  nixos/roles/router/keepalived/whq.conf
Labels: risk: 3, urgency: 3, auto-merge scheduled, backport fc-25.11-dev

#1763 devhost: reattach guest tap interfaces when the bridge interface is restarted
  changelog.d/20250902_155915_PL-133436-devhost-tap-reattachment_scriv.md
  nixos/roles/devhost/vm.nix
Labels: risk: 2, urgency: 2, auto-merge scheduled, backport fc-25.11-dev

#1781 [25.05] flake: fix versionsJson script after 21.05 removal from versions.json
  flake.nix
  release/package-versions.json
  release/versions.json
Labels: risk: 2, urgency: 5, auto-merge scheduled

#1809 Document opensearch ML/embedding usage
  doc/src/opensearch.md
Labels: risk: 1, urgency: 5, backport fc-25.11-dev

#1803 Set socket timeouts in router scripts when connecting to the directory
  pkgs/fc/agent/src/fc/manage/kea.py
  pkgs/fc/agent/src/fc/manage/zones.py
Labels: risk: 2, urgency: 2, auto-merge scheduled, backport fc-25.11-dev

#1822 nixos/nginx: add deprecation warning for `virtualHosts.<...>.emailACME`
  changelog.d/20250923_175331_HEAD_scriv.md
  nixos/services/nginx/default.nix
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1821 nixos/nginx: add warning for implicitly enabled `virtualHosts.<...>.enableACME`
  changelog.d/20250923_173244_HEAD_scriv.md
  nixos/services/nginx/default.nix
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1832 Doc fix opensearch
  doc/src/opensearch.md
Labels: risk: 1, urgency: 3, auto-merge scheduled, backport fc-25.11-dev

#1834 fc-maintenance: Fix crash on nullable summary properties
  pkgs/fc/agent/src/fc/maintenance/activity/tests/test_update.py
  pkgs/fc/agent/src/fc/maintenance/activity/update.py
  pkgs/fc/agent/src/fc/util/nixos.py
Labels: risk: 2, urgency: 4, auto-merge scheduled, backport fc-25.11-dev

#1820 Move VFS cache sysctl to backyserver role behind option
  changelog.d/20250923_130717_PL-133712-backy-vfs-cache-sysctl_scriv.md
  nixos/infrastructure/flyingcircus-physical.nix
  nixos/roles/backyserver.nix
Labels: risk: 2, urgency: 3, auto-merge scheduled, backport fc-25.11-dev
