Repository flyingcircusio/fc-nixos, pull requests merged in 2025-08, with the labels that each got.

#1709 ceph: switch monitor connection config to IP addresses.
  changelog.d/20250812_164131_PL-133752-avoid-ceph-mon-dns_scriv.md
  nixos/services/ceph/client.nix
Labels: risk: 3, urgency: 4, auto-merge scheduled, backport fc-25.11-dev

#1696 [25.05] nixos/platform: fixup currentPlatform version
  nixos/platform/default.nix
Labels: risk: 1, urgency: 1, auto-merge scheduled

#1737 Update static addresses in WHQ/office for renumbering
  nixos/platform/static.nix
  nixos/roles/router/bind/gocept.net.zone.static
Labels: risk: 2, urgency: 3, auto-merge scheduled, backport fc-24.11-dev, backport fc-25.11-dev

#1742 Update FRR to 10.1.4
  pkgs/overlay.nix
Labels: risk: 4, urgency: 2, auto-merge scheduled, backport fc-25.11-dev
