Repository flyingcircusio/fc-nixos, pull requests merged in 2025-04, with the labels that each got.

#1387 Ensure forwarding is enabled in the Docker role
  changelog.d/20250401_140923_PL-133589-docker-enable-forwarding_scriv.md
  nixos/roles/docker.nix
  nixos/roles/external_net/default.nix
Labels: risk: 2, urgency: 4

#1386 [PL-133028] add documentation for the statshost role with loki
  changelog.d/20250401_113338_PL-133028_loki-documentation_scriv.md
  doc/src/images/statshost/loki-basic-logging-dashboard.png
  doc/src/images/statshost/loki-datasource.png
  doc/src/images/statshost/loki-demo-dashboards.png
  doc/src/images/statshost/loki-explore.png
  doc/src/images/statshost/loki-simple-query-results.png
  doc/src/images/statshost/loki-simple-query.png
  doc/src/statshost.md
Labels: risk: 1, urgency: 2

#1402 Update Bird configuration for RZOB
  nixos/roles/router/bird2/default.nix
  nixos/roles/router/bird2/rzob.conf
Labels: risk: 5, urgency: 2

#1399 Check for convergent forwarding settings in Docker test
  tests/docker.nix
Labels: risk: 1, urgency: 1

#1392 Router: provide gateway services for layer 3 routed networks
  changelog.d/20250410_150528_PL-133324-routed-pub-router-support_scriv.md
  nixos/infrastructure/flyingcircus-physical.nix
  nixos/platform/network.nix
  nixos/roles/router/bird2-vrf-bridge.nix
  nixos/roles/router/default.nix
  pkgs/overlay.nix
Labels: risk: 3, urgency: 3

#1414 Only enable secondary Bird instance for managing VRF routes in the router role
  changelog.d/20250414_114754_PL-133324-vrf-bird-router-only_scriv.md
  nixos/roles/router/bird2-vrf-bridge.nix
Labels: risk: 2, urgency: 4

#1417 Don't set bridge options on routed networks in FRR config
  nixos/platform/network.nix
Labels: risk: 2, urgency: 4

#1416 devhost: refactor and fix graceful shutdown
  changelog.d/20250416_100658_PL-133536-fix-graceful-shutdown_scriv.md
  nixos/roles/devhost/fc.devhost/default.nix
  nixos/roles/devhost/fc.devhost/pyproject.toml
  nixos/roles/devhost/fc.devhost/src/fc/devhost/__init__.py
  nixos/roles/devhost/fc.devhost/src/fc/devhost/manager.py
  nixos/roles/devhost/fc.devhost/src/fc/devhost/qmp.py
  nixos/roles/devhost/fc.devhost/src/fc/devhost/timeout.py
  nixos/roles/devhost/vm.nix
Labels: risk: 2, urgency: 4

#1418 Update fc.qemu for routed pub support in cloud-init VM's
  changelog.d/20250416_165849_PL-133325-routed-networks-cloud-init_scriv.md
  pkgs/fc/default.nix
Labels: risk: 2, urgency: 4

#1424 adapt release-tools GHA to uv usage
  .github/workflows/auto-merge-check-pr.yaml
  .github/workflows/update-nixpkgs-cleanup.yaml
Labels: risk: 1, urgency: 4

#1423 fc.qemu: fix latency issue due to bottleneck rbd listing
  changelog.d/20250422_073148_PL-133632-fix-fc-qemu-rbd-ls_scriv.md
  changelog.d/20250422_125050_PL-133632-fix-fc-qemu-rbd-ls_scriv.md
  nixos/roles/kvm.nix
  pkgs/fc/default.nix
Labels: risk: 3, urgency: 5

#1427 KVM: provide DNS resolver services to routed guest interfaces over IPv6 using virtual router IP address
  changelog.d/20250423_101702_PL-133325-cidns-v6-dnat_scriv.md
  nixos/roles/kvm.nix
Labels: risk: 2, urgency: 3

#1420 Allow coturn to bind to privileged ports
  changelog.d/20250417_153006_PL-133419-coturn-private-users_scriv.md
  nixos/roles/coturn.nix
  tests/coturn.nix
Labels: risk: 2, urgency: 2

#1428 [PL-133642] roles/lamp: allow drv references in php.ini again
  changelog.d/20250424_101528_PL-133642-drv-references-in-php.ini_scriv.md
  nixos/roles/lamp.nix
  tests/lamp/vm-test.nix
Labels: risk: 1, urgency: 4

#1433 fc.agent: use `boot` to switch between NixOS release upgrades
  changelog.d/20250425_145920_PL-133570-24.11-require-boot-activation-for-distro-upgrades_scriv.md
  pkgs/fc/agent/fc/maintenance/activity/tests/test_update.py
  pkgs/fc/agent/fc/maintenance/activity/update.py
  pkgs/fc/agent/fc/manage/manage.py
  pkgs/fc/agent/fc/util/channel.py
  pkgs/fc/agent/fc/util/nixos.py
  pkgs/fc/agent/fc/util/tests/test_dmi_memory.py
  pkgs/fc/agent/fc/util/tests/test_nixos.py
Labels: risk: 4, urgency: 3

#1429 fc.agent: use `boot` to switch between NixOS release upgrades
  .github/workflows/pre-commit.yaml
  changelog.d/20250424_190850_PL-133570-24.05-require-boot-activation-for-distro-upgrades_scriv.md
  pkgs/fc/agent/fc/maintenance/activity/tests/test_update.py
  pkgs/fc/agent/fc/maintenance/activity/update.py
  pkgs/fc/agent/fc/manage/manage.py
  pkgs/fc/agent/fc/util/channel.py
  pkgs/fc/agent/fc/util/nixos.py
  pkgs/fc/agent/fc/util/tests/test_dmi_memory.py
  pkgs/fc/agent/fc/util/tests/test_nixos.py
Labels: risk: 4, urgency: 3

#1441 nixos/kernel: update verification kernel 6.6 -> 6.12
  changelog.d/20250429_132119_PL-133562-verification-kernel-6.12_scriv.md
  nixos/platform/kernel.nix
  pkgs/overlay.nix
  tests/kernelversions.nix
Labels: risk: 1, urgency: 3

#1444 [24.05] update zagy's root key
  changelog.d/20250429_133606_PL-133335-zagy-root-key_scriv.md
  nixos/platform/static.nix
Labels: risk: 1, urgency: 1

#1450 tests.gitlab: disable
  tests/default.nix
Labels: risk: 1, urgency: 2
