Repository flyingcircusio/fc-nixos, pull requests merged in 2025-07, with the labels that each got.

#1603 [25.05] Update addresses for WHQ in static platform configuration
  nixos/platform/static.nix
Labels: risk: 2, urgency: 3, auto-merge scheduled, backport fc-24.11-dev

#1606 [24.11] Update addresses for WHQ in static platform configuration
  nixos/platform/static.nix
Labels: risk: 2, urgency: 3, auto-merge scheduled

#1607 [24.11] update pinned nixpkgs to include sudo-1.9.17p1
  changelog.d/20250702_143646_PL-133836-sudo_scriv.md
  flake.lock
  release/versions.json
Labels: risk: 1, urgency: 5, auto-merge scheduled

#1618 flake: replace devenv with simple pkgs.mkShell
  dev-setup
  flake.lock
  flake.nix
Labels: backport fc-25.05-dev

#1619 [25.05] flake: replace devenv with simple pkgs.mkShell
  dev-setup
  flake.lock
  flake.nix
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1615 postgresql17: init role
  changelog.d/20250707_151945_PL-133728-pg17_scriv.md
  doc/src/postgresql.md
  doc/src/upgrade.md
  nixos/services/postgresql/default.nix
  pkgs/fc/agent/src/fc/util/postgresql.py
  tests/default.nix
  tests/postgresql/upgrade-with-extension.nix
  tests/postgresql/upgrade.nix
Labels: risk: 2, urgency: 2, auto-merge scheduled, backport fc-25.11-dev

#1633 PL-133864 feature flag xfs upgrades
  changelog.d/20250714_081049_fc-25.05-dev_scriv.md
  doc/src/upgrade.md
  nixos/platform/initrd.nix
  tests/initrd.nix
Labels: risk: 1, urgency: 4, auto-merge scheduled, backport fc-25.11-dev

#1635 initrd: fix eval for enableXFSUpgrades option
  nixos/platform/initrd.nix
Labels: risk: 1, urgency: 5, auto-merge scheduled, backport fc-25.11-dev

#1638 devhost: switch to kea as dhcp server
  changelog.d/20250715_095102_PL-133857-devhost-dhcp-issues_scriv.md
  nixos/roles/devhost/vm.nix
Labels: risk: 2, urgency: 3, backport fc-25.11-dev

#1648 [25.05] Revert systemd agent unit throttling changes
  changelog.d/20250715_145230_PL-133868-improve-qemu-throttling_scriv.md
  nixos/infrastructure/flyingcircus-virtual.nix
  nixos/platform/agent.nix
  nixos/platform/collect-garbage.nix
Labels: bug, risk: 1, urgency: 5, backport fc-24.11-dev, backport fc-25.11-dev

#1645 [FC-46599] doc/upgrade: make unsupportedness of multi-version upgrades explicit
  doc/src/upgrade.md
Labels: risk: 1, urgency: 1, auto-merge scheduled, backport fc-25.11-dev

#1637 [25.05] Patch FRR to stub out neighbour table management
  pkgs/fc/ping-on-tap/ping-on-tap.py
  pkgs/frr/0001-Don-t-throw-error-when-log-directory-already-exists.patch
  pkgs/frr/0002-zebra-dplane-sleep-after-writing-batches-to-netlink.patch
  pkgs/frr/0003-netlink-don-t-manage-kernel-neighbour-table-entries-.patch
  pkgs/overlay.nix
  tests/frr.nix
Labels: risk: 3, urgency: 3, auto-merge scheduled, backport fc-24.11-dev, backport fc-25.11-dev

#1657 Restore systemd agent unit throttling improvements for most VMs
  changelog.d/20250721_103204_PL-133877-partially-restore-age-nt-throttling-improvements_scriv.md
  nixos/infrastructure/flyingcircus-virtual.nix
  nixos/platform/agent.nix
  nixos/platform/collect-garbage.nix
Labels: risk: 3, urgency: 4, backport fc-24.11-dev, backport fc-25.11-dev

#1672 fc-manage check: display all Nix eval warnings
  changelog.d/20250729_105614_PL-133786-eval-warnings-agent_scriv.md
  nixos/platform/agent.nix
  pkgs/fc/agent/src/fc/manage/manage.py
  pkgs/fc/agent/src/fc/util/channel.py
  pkgs/fc/agent/src/fc/util/nixos.py
  pkgs/fc/agent/src/fc/util/tests/test_nixos.py
Labels: risk: 2, urgency: 2, auto-merge scheduled, backport fc-25.11-dev
