Repository flyingcircusio/fc-nixos, pull requests merged in 2025-06, with the labels that each got.

#1523 [PL-133737] fix a group issue with the alloy service when nginx is disabled
  changelog.d/20250602_103001_PL-133737-fix-alloy-service-wrong-groups_scriv.md
  nixos/services/nginx/default.nix
  tests/alloy.nix
  tests/default.nix
Labels: risk: 4, urgency: 5, auto-merge scheduled

#1524 [24.11] [PL-133737] fix a group issue with the alloy service when nginx is disabled
  changelog.d/20250602_103001_PL-133737-fix-alloy-service-wrong-groups_scriv.md
  nixos/services/nginx/default.nix
  tests/alloy.nix
  tests/default.nix
Labels: risk: 4, urgency: 5

#1525 Update Bird route-leaking service for renamed upstream services
  nixos/roles/router/bird2-vrf-bridge.nix
  pkgs/overlay.nix
Labels: risk: 4, urgency: 3, auto-merge scheduled

#1466 gitlab: fix registry port
  changelog.d/20250507_133919_PL-133568-gitlab-registry-port_scriv.md
  nixos/roles/gitlab.nix
  tests/gitlab.nix
Labels: risk: 1, urgency: 1, auto-merge scheduled

#1534 [PL-133751] tests: integrate interactive SSH debugging into our test suite
  nixos/infrastructure/testing.nix
  tests/default.nix
  tests/k3s/default.nix
  tests/lamp/vm-test.nix
  tests/make-test-python.nix
Labels: risk: 1, urgency: 2, auto-merge scheduled

#1545 fc-luks check: ignore no device match
  nixos/platform/full-disk-encryption.nix
  pkgs/fc/ceph/src/fc/ceph/luks/manage.py
Labels: risk: 1, urgency: 1, auto-merge scheduled

#1536 [24.11] doc/upgrade: percona 8.4 was never introduced in 24.11
  doc/src/upgrade.md
Labels: risk: 1, urgency: 4, auto-merge scheduled

#1520 xfs: enable default features
  changelog.d/20250528_185829_PL-133321-xfs-bigtime_scriv.md
  nixos/infrastructure/flyingcircus-physical.nix
  nixos/infrastructure/flyingcircus-virtual.nix
  nixos/platform/default.nix
  nixos/platform/initrd.nix
  nixos/roles/kvm.nix
  pkgs/fc/agent/src/fc/maintenance/maintenance.py
  pkgs/fc/agent/src/fc/manage/cli.py
  pkgs/fc/agent/src/fc/manage/tests/test_cli.py
  pkgs/fc/agent/src/fc/util/enc.py
  pkgs/fc/agent/src/fc/util/tests/test_enc.py
  tests/default.nix
  tests/initrd.nix
Labels: risk: 4, urgency: 1, auto-merge scheduled

#1559 [25.05] Disable suppression of hung task warnings in VMs
  nixos/infrastructure/flyingcircus-virtual.nix
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1558 [25.05] Add agent option to immediately reboot when activating new configuration
  changelog.d/20250610_183716_PL-133308-agent-stc-boot_scriv.md
  pkgs/fc/agent/src/fc/manage/cli.py
  pkgs/fc/agent/src/fc/manage/manage.py
  pkgs/fc/agent/src/fc/manage/tests/test_cli.py
  pkgs/fc/agent/src/fc/util/channel.py
Labels: risk: 1, urgency: 1, auto-merge scheduled

#1543 Add agent option to immediately reboot when activating new configuration
  changelog.d/20250610_183716_PL-133308-agent-stc-boot_scriv.md
  pkgs/fc/agent/src/fc/manage/cli.py
  pkgs/fc/agent/src/fc/manage/manage.py
  pkgs/fc/agent/src/fc/manage/tests/test_cli.py
  pkgs/fc/agent/src/fc/util/channel.py
Labels: risk: 1, urgency: 1, auto-merge scheduled

#1517 [PL-133563] services/redis: get rid of IFD for generating the Redis password
  changelog.d/20250324_095007_PL-133563-redis-remove-ifd_scriv.md
  nixos/roles/gitlab.nix
  nixos/services/redis.nix
  tests/gitlab.nix
  tests/redis.nix
Labels: risk: 4, urgency: 3, auto-merge scheduled

#1567 [25.05] Add new networks to RZOB keepalived configuration
  nixos/roles/router/keepalived/rzob.conf
Labels: risk: 3, urgency: 3, auto-merge scheduled

#1572 imagemagick: re-introduce imagemagick7 aliases
  pkgs/overlay.nix
Labels: risk: 1, urgency: 4, auto-merge scheduled

#1566 gha: Add backport action
  .github/workflows/backport.yaml
Labels: risk: 1, urgency: 3

#1571 [PL-133160] nixos/platform: don't discard user-defined unfree/insecure packages
  changelog.d/20250620_171028_PL-133160-merge-insecure-unfree-declarations_scriv.md
  default.nix
  flake.lock
  nixos/platform/default.nix
  release/versions.json
Labels: risk: 2, urgency: 1

#1580 mailserver: update simple-nixos-mailserver
  doc/src/mailserver.md
  flake.lock
  flake.nix
  nixos/roles/mailserver.nix
  nixos/services/mail/default.nix
  nixos/services/mail/rspamd.nix
  release/versions.json
Labels: risk: 2, urgency: 4, auto-merge scheduled

#1560 [24.11] linuxKernelStable: 6.6 -> 6.12
  changelog.d/20250616_162350_PL-133760-kernel-612_scriv.md
  nixos/platform/default.nix
  pkgs/fc/default.nix
  pkgs/overlay.nix
  tests/k3s/monitoring.nix
  tests/kernelconfig.nix
  tests/kernelversions.nix
  tests/matomo.nix
  tests/opensearch_dashboards.nix
Labels: risk: 3, urgency: 5

#1570 s3users: report secret key back to the directory
  changelog.d/20250620_101137_PL-133656-s3-report-secret-key-to-directory_scriv.md
  pkgs/fc/agent/src/fc/manage/s3users.py
  pkgs/fc/agent/src/fc/manage/tests/test_s3users.py
Labels: risk: 3, urgency: 1, auto-merge scheduled, backport fc-24.11-dev

#1591 doc/upgrade: several additions
  doc/src/upgrade.md
Labels: risk: 1, urgency: 3, auto-merge scheduled

#1590 linuxKernelStable: 6.6 -> 6.12
  doc/src/upgrade.md
  nixos/platform/default.nix
  pkgs/fc/default.nix
  pkgs/overlay.nix
  tests/k3s/monitoring.nix
  tests/kernelconfig.nix
  tests/kernelversions.nix
  tests/matomo.nix
  tests/opensearch_dashboards.nix
Labels: risk: 2, urgency: 4, auto-merge scheduled

#1592 fc-slurm: adapt to pyslurm API change
  pkgs/fc/agent/src/fc/util/slurm.py
  pkgs/fc/agent/src/fc/util/tests/test_slurm.py
Labels: risk: 1, urgency: 4, auto-merge scheduled

#1587 ceph-load-vm-images: only lock image if there is no lock yet
  changelog.d/20250625_160625_fc-25.05-dev_scriv.md
  pkgs/fc/ceph/src/fc/ceph/maintenance/images_nautilus.py
Labels: risk: 3, urgency: 2, auto-merge scheduled, backport fc-24.11-dev

#1601 doc/upgrade/slurm: add link to upstream release notes
  doc/default.nix
  doc/src/upgrade.md
Labels: risk: 1, urgency: 3, auto-merge scheduled
