Repository flyingcircusio/fc-nixos, pull requests merged in 2025-03, with the labels that each got.

#1329 overlay, php: build php82/83 with patched curl on hydra
  pkgs/overlay.nix
Labels: risk: 1, urgency: 3

#1335 Unload USB XHCI driver at shutdown on hardware
  changelog.d/20250311_172519_PL-133421-shutdown-unload-xhci-driver_scriv.md
  nixos/infrastructure/flyingcircus-physical.nix
Labels: risk: 1, urgency: 4

#1339 devhost: improve error handling in image download
  changelog.d/20250313_104722_PL-133539-dont-save-broken-devhost-base-image_scriv.md
  nixos/roles/devhost/fc-devhost.py
Labels: risk: 1, urgency: 3

#1331 add tracing for when evaluation recurses into 21.05 nixpkgs instance
  changelog.d/20250310_143121_PL-133522-trace-2105-usage_scriv.md
  pkgs/overlay.nix
Labels: risk: 1, urgency: 1

#1317 tests/router: remove superfluous assertions
  tests/router/default.nix
Labels: risk: 1, urgency: 1

#1338 devhost: stop VMs gracefully
  changelog.d/20250313_104234_PL-133536-stop-devhost-vms-gracefully_scriv.md
  nixos/roles/devhost/vm.nix
Labels: risk: 2, urgency: 3

#1310 monitoring: make port speed monitoring more flexible (and sane)
  changelog.d/20250227_160510_PL-133472-interface-check-minimal-speeds-only_scriv.md
  nixos/infrastructure/flyingcircus-physical.nix
  nixos/lib/network.nix
  nixos/platform/static.nix
Labels: risk: 1, urgency: 4

#1286 testing: show systemd journal output
  nixos/platform/default.nix
  nixos/platform/full-disk-encryption.nix
  nixos/platform/systemd.nix
  nixos/roles/jitsi/default.nix
  tests/backy_volumes.nix
  tests/ceph-nautilus.nix
  tests/fde-tooling.nix
Labels: risk: 2, urgency: 1

#1334 [FC-43451] nixos/rabbitmq: install rabbitmqadmin-ng by default
  changelog.d/20250305_120319_fc-24.11-dev_scriv.md
  doc/src/rabbitmq.md
  nixos/services/rabbitmq/default.nix
Labels: risk: 1, urgency: 2

#1346 [24.05] rabbitmq-server: 3.12.13 -> 3.13.7
  changelog.d/20250318_115307_PL-133542-rabbitmq-update_scriv.md
  flake.lock
  release/package-versions.json
  release/versions.json
Labels: risk: 2, urgency: 4

#1333 nginx,acme: make sensu checks work for non-HTTPS usage
  changelog.d/20250311_140206_PL-131278-ssl-checks-non-https_scriv.md
  nixos/platform/acme.nix
  nixos/services/nginx/default.nix
Labels: risk: 2, urgency: 4

#1350 varnish: fix check-varnish-http check
  changelog.d/20250319_160130_PL-133554-varnish_http_awk_scriv.md
  nixos/roles/webproxy.nix
Labels: risk: 1, urgency: 5

#1351 Ensure that IPv4 forwarding is disabled by default
  changelog.d/20250319_173208_PL-133557-default-forwarding-without-firewall_scriv.md
  nixos/lib/utils.nix
  nixos/platform/network.nix
  nixos/roles/devhost/default.nix
  nixos/roles/external_net/default.nix
  nixos/roles/router/default.nix
  tests/frr.nix
  tests/network/default.nix
  tests/testlib.nix
Labels: risk: 2, urgency: 4

#1345 mailserver: add ip_blocklists option and sensu checks
  changelog.d/20250318_115032_PL-133519-email-blocklist_scriv.md
  nixos/roles/mailserver.nix
  nixos/services/mail/default.nix
Labels: risk: 2, urgency: 2

#1342 flyingcircus.services.rabbitmq: enable prometheus exporter, through telegraf
  changelog.d/20250314_174504_PL-133391-rabbitmq-prometheus_exporter_scriv.md
  nixos/platform/monitoring.nix
  nixos/services/rabbitmq/default.nix
  nixos/services/telegraf/default.nix
Labels: risk: 2, urgency: 1

#1341 fc.qemu improvements for test stability
  .pre-commit-config.yaml
  changelog.d/20250314_142141_PL-133300-fix-fc-qemu-test-flakiness_scriv.md
  nixos/infrastructure/dev-vm.nix
  nixos/lib/ceph-common.nix
  nixos/platform/static.nix
  nixos/roles/ceph/osd.nix
  nixos/roles/consul/default.nix
  nixos/roles/kvm.nix
  nixos/services/ceph/client.nix
  nixos/services/consul/default.nix
  pkgs/fc/agent/fc/maintenance/activity/vm_change.py
  pkgs/fc/agent/fc/util/tests/test_dmi_memory.py
  pkgs/fc/ceph/default.nix
  pkgs/fc/ceph/src/fc/ceph/lvm.py
  pkgs/fc/ceph/src/fc/ceph/mon/nautilus.py
  pkgs/fc/ceph/src/fc/ceph/osd/nautilus.py
  pkgs/fc/ceph/src/fc/ceph/util/timeout.py
  pkgs/fc/check-ceph/nautilus/fc/check_ceph/check_snapshot_restore.py
  pkgs/fc/default.nix
  pkgs/fc/qemu/default.nix
  tests/default.nix
  tests/kvm_host_ceph-nautilus.nix
Labels: risk: 4, urgency: 2

#1355 codestyle-template: update
  .pre-commit-config-local.yaml
  .pre-commit-config.yaml
Labels: risk: 3, urgency: 2

#1363 redis: remove ifd for password
  changelog.d/20250324_095007_PL-133563-redis-remove-ifd_scriv.md
  nixos/roles/gitlab.nix
  nixos/services/redis.nix
  tests/gitlab.nix
Labels: risk: 2, urgency: 3

#1354 fclib.utils.python3BinFromFile: allow passing libraries and executables
  nixos/lib/utils.nix
  nixos/platform/journalbeat.nix
  nixos/roles/check-varnish-http.py
  nixos/roles/consul/default.nix
  nixos/roles/webproxy.nix
  nixos/services/consul/default.nix
Labels: risk: 2, urgency: 2

#1250 Add cloud-init compatibility for Ubuntu VMs
  changelog.d/20250124_092043_PL-133325-ubuntu-vms_scriv.md
  pkgs/fc/agent/fc/manage/createvm.py
  pkgs/fc/agent/fc/manage/qemu.py
  pkgs/fc/default.nix
  pkgs/fc/qemu/default.nix
Labels: risk: 3, urgency: 2

#1371 nginx: make HTTPS sensu check work for vhost name != serverName
  nixos/services/nginx/default.nix
Labels: risk: 2, urgency: 4

#1368 ipmi: make changing the IPMI admin username optional
  changelog.d/20250325_175057_PL-133561-make-managing-ipmi-admin-names-optional_scriv.md
  nixos/platform/ipmi.nix
Labels: risk: 1, urgency: 1

#1353 Add tests to check forwarding sysctls
  tests/default.nix
  tests/ip-forward.nix
  tests/testlib.nix
Labels: risk: 1, urgency: 1

#1374 bump nixpkgs to include pgvectorscale extension
  changelog.d/20250327_224109_os-pgvector_scriv.md
  flake.lock
  release/versions.json
Labels: risk: 2, urgency: 4
